
EXAMPLES= example0.java example1.java example1a.java example2.java \
          example3.java example4.java graph.java example6.java \
          parse1d.java parser.java example4a.java example2a.java \
	  parse2d.java

examples:
	javac -d ../classes $(EXAMPLES)
